import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Providers from "./providers";
import Navbar from "@/components/ui/navbar";

import "./globals.css";
import Sidebar from "@/components/ui/sidebar/sidebar";
import { Box } from "@mui/material";

import { ThemeRegistry } from "../lib/ThemeRegistry";
import { ThemeModeProvider } from "@/lib/theme-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeModeProvider>
          <ThemeRegistry>
            <Providers>
              <Box sx={{ display: "flex" }}>
                <Sidebar />
                <Box sx={{ width: "100%" }}>
                  <Navbar />

                  <Box sx={{ padding: "48px" }}>{children}</Box>
                </Box>
              </Box>
            </Providers>
          </ThemeRegistry>
        </ThemeModeProvider>
      </body>
    </html>
  );
}
